---
- name: Converge
  hosts: all
  roles:
    - role: abdennour.bootstrap

  pre_tasks:
  - name: bootstrap user does not exist
    user:
      name: "{{ bootstrap_username }}"
      state: absent
    changed_when: false
  post_tasks:
  - name: bootstrap user exists
    user:
      name: "{{ bootstrap_username }}"
      state: present
    changed_when: false