---
- name: Converge
  hosts: all
  vars:
    new_user: anyname
    key_path: /tmp/id_ssh_rsa

  tasks:
  - name: role is imported
    import_role:
      name: abdennour.bootstrap
    vars:
      bootstrap_publickey_path: "{{ key_path }}.pub"
      bootstrap_username: "{{ new_user }}"
  pre_tasks:
  - name: generate key pair
    openssh_keypair:
      path: "{{ key_path }}"
    delegate_to: localhost
  post_tasks:
  - name: the new bootstrap user can authenticate passwordless
    ping:
    remote_user: "{{ bootstrap_username }}"
    become: yes
    vars:
      ansible_ssh_private_key_file: "{{ key_path }}"